config/routes.rb
Rails.application.routes.draw do
  resources :lines, except:[:show, :destroy]
  resources :users, except:[:show, :destroy]
  resources :ip_phones, except:[:show, :destroy]
  resources :devices, except:[:show, :destroy]
  resources :offices, except:[:show, :destroy]
  resources :internals, except:[:show, :destroy]
  resources :telephone_switches, except:[:show, :destroy]
  resources :form_options, except:[:show, :destroy]
  resources :device_models, only:[:new, :create]
  resources :csv_report_lines, only:[:new, :create, :show], as: :reports
  resources :plans, only:[:new, :create]
  resources :accounts, only:[:new, :create]
  get 'adminzone/index'
  devise_for :admins
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  #t.string "name"
  #t.string "lastname"
  #t.string "dni"
  #t.bigint "office_id", null: false
  ############ RELATIONS
  belongs_to :office
  has_many :lines
  ############ VALIDATIONS
  validates :name, presence:true
  validates :lastname, presence:true
  validates :office_id, presence:true
  ############ CALLBACKS

  ############ METHODS
  def get_fullname
    return "#{self.lastname.upcase} #{self.name.titleize}"
  end#get_fullname

  def get_dni_formatted
    unless self.dni.empty?
      return self.dni.reverse.insert(6,'.').insert(3,'.').reverse
    end
    return self.dni
  end#get_dni_formatted

  def get_office_fullname
    return self.office.get_fullname
  end

  ############ CLASS METHODS

  #############CALLBACKS METHODS

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_form_options, only: [:new, :create, :edit, :update]
  def index
    @users = User.all
    @new_user = User.new
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save!
        flash[:notice] ="Creado exitosamente"
        format.html {redirect_to users_path}
      else
        flash[:danger] ="Contiene errores"
        format.html {redirect_to users_path, alert:"ERROR"}
        #
      end
    end
  end

  def show
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:notice] ="Editado exitosamente"
        format.html {redirect_to users_path}
      else
        flash[:danger] ="Contiene errores"
        format.html {redirect_to users_path}
      end
    end
  end

  def destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :lastname, :dni, :office_id)
  end

  def set_form_options
    @office_options = Office.get_office_options
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="modal fade" id="new-user-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Formulario de Usuarios</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%= form_with(model: user, url:url, method:method) do |usr| %>

    <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

      <div class="modal-body">

        <div class="form-group">
          <%= usr.label :name, "Nombre" %>
          <%= usr.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= usr.label :lastname, "Apellido" %>
          <%= usr.text_field :lastname, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= usr.label :dni, "DNI" %>
          <%= usr.text_field :dni, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= usr.label :office_id, "Oficina" %>
          <%= usr.select :office_id, @office_options.map { |val| [val[0],val[1]] }, {}, {class:"form-control"} %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <%= usr.submit "Guardar", class:"btn btn-primary" %>
      </div>

    <% end %>

  </div>
</div>
</div>

app/views/users/edit.js.erb
$('#new-user').html("<%= j (render 'form', user:@user, url:user_path, method:'PUT')%>");
$('#new-user-modal').modal('show')
$('#new-user').slideDown(350)

app/views/users/index.html.erb
<h1><i class="fas fa-users"></i> Usuarios</h1>
<% if current_admin.can_create? %>
  <%= link_to "Nuevo usuario", new_user_path, remote: :true, class:"btn btn-success" %>
<% end %>

<% unless @users.count == 0 %>
<table class="table table-stripped table-hover table-dark">
  <thead>
    <th>Nombre</th>
    <th>DNI</th>
    <th>Oficina</th>
    <th>Líneas</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td class="align-middle"><%= user.get_fullname %></td>
      <td class="align-middle"><%= user.get_dni_formatted %></td>
      <td class="align-middle"><%= user.get_office_fullname %></td>
      <td class="align-middle"><%= user.lines.count %></td>
      <td class="align-middle">
        <%= render "shared/buttons/edit_button_simple",
              link_url: edit_user_path(user),
              link_icon: "fas fa-user-edit",
              link_text: "",
              link_class: "btn btn-warning",
              link_remote: :true %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div class="alert alert-warning" role="alert">
  <h4 class="alert-heading">No hay usuarios cargados!</h4>
  <p>Un adminsitrador con permisos de acceso debería comenzar a agregarlos.</p>
  <span class="fa-stack fa-2x">
  <i class="fas fa-user-plus fa-stack-2x pull-left"></i>

</span>
</div>
<% end %>

<!-- Experimantal -->
<div class="" id="new-user">

</div>

app/views/users/new.js.erb
$('#new-user').html("<%= j (render 'form', user:@user, url:users_path, method:'POST')%>");
$('#new-user-modal').modal('show')
$('#new-user').slideDown(350)