config/routes.rb
Rails.application.routes.draw do
  resources :lines, except:[:show, :destroy]
  resources :users, except:[:show, :destroy]
  resources :ip_phones, except:[:show, :destroy]
  resources :devices, except:[:show, :destroy]
  resources :offices, except:[:show, :destroy]
  resources :internals, except:[:show, :destroy]
  resources :telephone_switches, except:[:show, :destroy]
  resources :form_options, except:[:show, :destroy]
  resources :device_models, only:[:new, :create]
  resources :csv_report_lines, only:[:new, :create, :show], as: :reports
  resources :plans, only:[:new, :create]
  resources :accounts, only:[:new, :create]
  get 'adminzone/index'
  devise_for :admins
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_alerts.html.erb
<div style="">
  <% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Info:</strong> <%= flash[:notice] %>
    </div>
  <% elsif flash[:danger] %>
  <div class="alert alert-danger alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Algo malio sal:</strong> <%= flash[:danger] %>
  </div>
  <% end %>
</div>

app/views/shared/_nav_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <%= link_to(root_path, class: "navbar-brand brand-title vertical-align") do %>
    <span class="fa-stack fa-1x vertical-align">
      <i class="fas fa-mobile fa-stack-2x"></i>
      <i class="fas fa-sim-card fa-stack-1x" style="color:#70326F"></i>
    </span>
      Telefonía On Rails
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to(root_path, class: "nav-link btn") do %>
          <i class="fas fa-tachometer-alt fa-2x"></i>
          <div class="">
            Dashboard
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(lines_path, class: "nav-link btn") do %>
          <i class="fas fa-sim-card fa-2x"></i>
          <div class="">
            Líneas
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(devices_path, class: "nav-link btn") do %>
          <i class="fas fa-mobile-alt fa-2x"></i>
          <div class="">
            Equipos
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(users_path, class: "nav-link btn") do %>
          <i class="fas fa-users fa-2x"></i>
          <div class="">
            Usuarios
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(internals_path, class: "nav-link btn") do %>
          <i class="fas fa-phone fa-2x"></i>
          <div class="">
            Internos
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(ip_phones_path, class: "nav-link btn") do %>
          <i class="fas fa-fax fa-2x"></i>
          <div class="">
            Tel. IP
          </div>
        <% end %>
      </li>

    </ul>
    <ul class="navbar-nav">
    <% if admin_signed_in? %>
      <li class="nav-item">
        <%= link_to("#", class: "nav-link btn") do %>
        <i class="fas fa-cog fa-2x"></i>
        <div class="">
          Editar
        </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(destroy_admin_session_path, method: :delete, class: "nav-link btn") do %>
        <i class="fas fa-user-slash fa-2x"></i>
        <div class="">
          Cerrar Sesión
        </div>
        <% end %>
      </li>
      <% unless current_admin.access_level < 3 %>
      <li class="nav-item">
        <%= link_to(adminzone_index_path, class: "nav-link btn") do %>
        <i class="fas fa-user-tie fa-2x"></i>
        <div class="">
          AdminZone
        </div>
        <% end %>
      </li>
      <% end %>
    <% end %>
    <li class="nav-item">
      <%= link_to("#", class: "nav-link btn") do %>
      <i class="fas fa-question-circle fa-2x"></i>
      <div class="">
        Acerca de
      </div>
      <% end %>
    </li>
  </ul>
  </div>
</nav>