config/routes.rb
Rails.application.routes.draw do
  resources :lines, except:[:show, :destroy]
  resources :users, except:[:show, :destroy]
  resources :ip_phones, except:[:show, :destroy]
  resources :devices, except:[:show, :destroy]
  resources :offices, except:[:show, :destroy]
  resources :internals, except:[:show, :destroy]
  resources :telephone_switches, except:[:show, :destroy]
  resources :form_options, except:[:show, :destroy]
  resources :device_models, only:[:new, :create]
  resources :csv_report_lines, only:[:new, :create, :show], as: :reports
  resources :plans, only:[:new, :create]
  resources :accounts, only:[:new, :create]
  get 'adminzone/index'
  devise_for :admins
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/internal.rb
class Internal < ApplicationRecord
  #t.string "name"
  #t.string "number"
  #t.string "office_id"
  #t.string "kind"
  #t.string "telephone_switch_id"
  #t.boolean "publishable"
  ########### RELATIONS
  belongs_to :telephone_switch
  belongs_to :office
  ########### VALIDATIONS
  validates :name, presence: true
  validates :number, presence: true
  ########### METHODS
  scope :by_kind, ->(kind) { where(kind: kind) }
  scope :by_telephone_switch, ->(id) { where(telephone_switch_id: id) }
  ########### METHODS
  def get_name
    return self.name
  end#get_name

  def get_number
    return self.number
  end#get_number

  def get_office
    return self.office.get_fullname
  end#get_office

  def get_kind
    return self.kind
  end#get_kind

  def get_telephone_switch
    return self.telephone_switch.get_name
  end#get_telephone_switch

  def publishable?
    return self.publishable
  end

  ########### CLASS METHODS
  def self.get_kind_options
    return FormOption.get_options_for("internal_kind")
  end#get_kind_options

  def self.get_telephone_switch_options
    return TelephoneSwitch.get_telephone_switch_options
  end#get_telephone_switch_options

  def self.get_office_options
    return Office.get_office_options
  end#get_office_options
  ###########
end

app/controllers/internals_controller.rb
class InternalsController < ApplicationController
  include Pagy::Backend
  before_action :set_internal, only: [:show, :edit, :update, :destroy]
  before_action :set_form_options, only: [:new, :create, :edit, :update]
  def index
    @pagy, @internals = pagy(Internal.all)
    #@internals = Internal.all
    @new_internal = Internal.new
  end

  def new
    @internal = Internal.new
    #@internal.publishable = true #Error?
    respond_to do |format|
      format.js
    end
  end

  def create
    @internal = Internal.new(internal_params)
    respond_to do |format|
      if @internal.save!
        flash[:notice] = "Creado exitosamente"
        format.html {redirect_to internals_path}
        format.js
      else
        flash[:danger] ="Contiene errores"
        format.html {redirect_to internals_path, alert:"ERROR"}
        #
      end
    end
  end

  def show
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @internal.update(internal_params)
        flash[:notice] ="Editado exitosamente"
        format.html {redirect_to internals_path}
      else
        flash[:danger] ="Contiene errores"
        format.html {redirect_to internals_path}
      end
    end
  end

  def destroy
  end

  private
  def set_internal
    @internal = Internal.find(params[:id])
  end

  def internal_params
    params.require(:internal).permit(:name, :number, :kind, :publishable, :office_id, :telephone_switch_id)
  end

  def set_form_options
    @kind_options = Internal.get_kind_options
    @office_options = Internal.get_office_options
    @telephone_switch_options = Internal.get_telephone_switch_options
  end
end

app/helpers/internals_helper.rb
module InternalsHelper
end

app/views/internals/_form.html.erb
<div class="modal fade" id="form-internal-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Interno Telefónico</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%= form_with(model: internal, url:url, method:method) do |i| %>

      <div class="modal-body">

        <div class="form-group">
          <%= i.label :telephone_switch_id, "Central" %>
          <%= i.select :telephone_switch_id, @telephone_switch_options.map { |option| [option[0],option[1]]  }, {}, {class:"form-control"} %>
        </div>

        <div class="form-group">
          <%= i.label :office_id, "Oficina" %>
          <%= i.select :office_id, @office_options.map { |option| [option[0],option[1]]  }, {}, {class:"form-control"} %>
        </div>

        <div class="form-group">
          <%= i.label :name, "Nombre" %>
          <%= i.text_field :name, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= i.label :number, "Número" %>
          <%= i.text_field :number, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= i.label :publishable, "Publicable" %>
          <%= i.check_box :publishable,class: "checkbox" %>
        </div>

        <div class="form-group">
          <%= i.label :kind, "Tipo de línea" %>
          <%= i.select :kind, @kind_options.map { |val| [val,val]}, {}, {class:"form-control"} %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <%= i.submit "Guardar", class:"btn btn-primary" %>
      </div>

    <% end %>

  </div>
</div>
</div>

app/views/internals/_internal.html.erb
<tr>
  <td class="align-middle"><%= internal.get_name %></td>
  <td class="align-middle"><%= internal.get_number %></td>
  <td class="align-middle"><%= internal.get_office %></td>
  <td class="align-middle"><%= internal.get_kind %></td>
  <td class="align-middle"><%= internal.get_telephone_switch %></td>
  <td class="align-middle">
    <% if current_admin.can_create? %>
    <%= render "shared/buttons/edit_button_simple",
          link_url: edit_internal_path(internal),
          link_icon: "fas fa-edit",
          link_text: "",
          link_class: "btn btn-warning",
          link_remote: :true %>
    <% end %>
  </td>
</tr>

app/views/internals/create.js.erb
$('#form-internal-modal').modal('hide')
$('table#internals-table tbody').append("<%= j render @internal %>")

app/views/internals/edit.js.erb
$('#form-internal').html("<%= j (render 'form', internal:@internal, url:internal_path, method:'PUT')%>");
$('#form-internal-modal').modal('show')
$('#form-internal').slideDown(350)

app/views/internals/index.html.erb
<h1><i class="fas fa-phone"></i> Internos Telefónicos</h1>

<% if current_admin.can_create? %>
  <%= link_to "Nuevo Interno", new_internal_path, remote: :true, class:"btn btn-success" %>
<% end %>

<% unless @internals.count == 0 %>
<table class="table table-stripped table-hover table-dark" id="internals-table">
  <thead>
    <th>Nombre</th>
    <th>Número</th>
    <th>Oficina</th>
    <th>Tipo</th>
    <th>Central</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <%= render @internals %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>
<% if current_admin.can_create? %>
  <%= link_to "Nuevo Interno", new_internal_path, remote: :true, class:"btn btn-success" %>
<% end %>

<% else %>
<div class="alert alert-warning" role="alert">
  <h4 class="alert-heading">No hay internos cargados!</h4>
  <p>Un adminsitrador con permisos de acceso debería comenzar a agregarlos.</p>
  <span class="fa-stack fa-2x">
  <i class="fas fa-phone-square fa-stack-2x pull-left"></i>
  <i class="fas fa-plus fa-stack-1x" style="color:Lightgreen"></i>
</span>
</div>
<% end %>

<!-- Experimantal -->
<div class="" id="form-internal">

</div>

app/views/internals/new.js.erb
$('#form-internal').html("<%= j (render 'form', internal:@internal, url:internals_path, method:'POST')%>");
$('#form-internal-modal').modal('show')
$('#form-internal').slideDown(350)