config/routes.rb
Rails.application.routes.draw do
  resources :lines, except:[:show, :destroy]
  resources :users, except:[:show, :destroy]
  resources :ip_phones, except:[:show, :destroy]
  resources :devices, except:[:show, :destroy]
  resources :offices, except:[:show, :destroy]
  resources :internals, except:[:show, :destroy]
  resources :telephone_switches, except:[:show, :destroy]
  resources :form_options, except:[:show, :destroy]
  resources :device_models, only:[:new, :create]
  resources :csv_report_lines, only:[:new, :create, :show], as: :reports
  resources :plans, only:[:new, :create]
  resources :accounts, only:[:new, :create]
  get 'adminzone/index'
  devise_for :admins
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/adminzone_controller.rb
class AdminzoneController < ApplicationController
  def index
    @admins = Admin.all
    @form_options = FormOption.all.order(:entityName)
    @accounts = Account.all
    @plans = Plan.all
    @offices = Office.get_ordered_by_organization_chart.collect()
    @device_models = DeviceModel.all
    @line_statuses = FormOption.get_options_for('line_status')
    @reports = CsvReportLine.all
    @telephone_switches = TelephoneSwitch.all
    @internals = Internal.all
  end
end

app/helpers/adminzone_helper.rb
module AdminzoneHelper
end

app/views/adminzone/_accounts_table.html.erb
<table class="table table-hover table-stripped table-dark">
  <thead>
    <th>Cuenta</th>
    <th>Número</th>
    <% @line_statuses.each do |ls| %>
    <th><%= ls %></th>
    <% end %>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @accounts.each do |a| %>
    <tr>
      <td class="align-middle"><%= a.get_name %></td>
      <td class="align-middle"><%= a.get_number %></td>

      <% @line_statuses.each do |ls| %>
      <td class="align-middle"><%=  %></td>
      <% end %>

      <td class="align-middle"><%=  %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/adminzone/_admins_table.html.erb
<table class="table table-hover table-stripped table-dark">
  <thead>
    <th>E-mail</th>
    <th>Permisos</th>
    <th>Última Sesión</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @admins.each do |a| %>
    <tr>
      <td class="align-middle"><%= a.get_email %></td>
      <td class="align-middle"><%= a.get_permissions %></td>
      <td class="align-middle"><%= a.get_last_session %></td>
      <td class="align-middle">...</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/adminzone/_device_models_table.html.erb
<table class="table table-hover table-stripped table-dark">
  <thead>
    <th>Marca</th>
    <th>Nombre modelo</th>
    <th>SIM</th>
    <th>Banda</th>
    <th>S.O. (Act.)</th>
    <th>RAM</th>
    <th>ROM</th>
    <th>Frec. CPU</th>
    <th>Núcleos (CPU)</th>
    <th>Pantalla</th>
    <th>Cámaras</th>
    <th>Batería</th>
    <th>USB</th>
    <th>Fecha</th>
    <th>Cant.</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @device_models.each do |dm| %>
    <tr>
      <td class="align-middle"><%= dm.get_mark %></td>
      <td class="align-middle"><%= dm.get_full_model_name %></td>
      <td class="align-middle"><%= dm.get_slot_sim %></td>
      <td class="align-middle"><%= dm.get_band %></td>
      <td class="align-middle"><%= dm.get_os_max %></td>
      <td class="align-middle"><%= dm.get_ram_size %></td>
      <td class="align-middle"><%= dm.get_rom_size %></td>
      <td class="align-middle"><%= dm.get_cpu_freq_max %></td>
      <td class="align-middle"><%= dm.get_cores %></td>
      <td class="align-middle"><%= dm.get_full_screen_size %></td>
      <td class="align-middle"><%= dm.get_cams_mp %></td>
      <td class="align-middle"><%= dm.get_battery %></td>
      <td class="align-middle"><%= dm.get_usb_type %></td>
      <td class="align-middle"><%= dm.get_announce_date %></td>
      <td class="align-middle">#</td>
      <td class="align-middle">...</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/adminzone/_form_options_table.html.erb
<table class="table table-hover table-stripped table-dark" id="form-options-table">
  <thead>
    <th>Entidad</th>
    <th>Campo</th>
    <th>Valor</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <%= render partial: 'form_options/form_option', collection: @form_options %>
  </tbody>
</table>

app/views/adminzone/_offices_table.html.erb
<table class="table table-hover table-stripped table-dark" id="offices-table">
  <thead>
    <th>Nombre</th>
    <th>Pertenece a</th>
    <th>Líneas</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <%= render partial: 'offices/office', collection: @offices %>
  </tbody>
</table>

app/views/adminzone/_plans_table.html.erb
<table class="table table-hover table-stripped table-dark">
  <thead>
    <th>Nombre</th>
    <th>Código</th>
    <% @accounts.each do |a| %>
    <th><%= a.get_name %></th>
    <% end %>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @plans.each do |a| %>
    <tr>
      <td class="align-middle"><%= a.get_name %></td>
      <td class="align-middle"><%= a.get_code_name %></td>

      <% @accounts.each do |ls| %>
      <td class="align-middle">#</td>
      <% end %>

      <td class="align-middle"><%=  %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/adminzone/_reports_table.html.erb
<table class="table table-hover table-stripped table-dark">
  <thead>
    <th>Cuenta</th>
    <th>Fecha</th>
    <th>Líneas</th>
    <th>Opciones</th>
  </thead>
  <tbody>
    <% @reports.each do |r| %>
    <tr>
      <td class="align-middle"><%= r.get_account %></td>
      <td class="align-middle"><%= r.get_date %></td>
      <td class="align-middle"><%= r.get_count_lines %></td>
      <td class="align-middle">
        <%= link_to report_path(r), class: "btn btn-info" do %>
          <i class="fas fa-eye"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/adminzone/_telephone_switches_table.html.erb
<table class="table table-hover table-stripped table-dark" id="telephone-switches-table">
  <thead>
    <th>Nombre</th>
    <th>Cabecera</th>
    <th>Internos</th>
    <th>IP</th>

    <th>Opciones</th>
  </thead>
  <tbody>
    <%= render partial: 'telephone_switches/telephone_switch', collection: @telephone_switches %>
  </tbody>
</table>

app/views/adminzone/index.html.erb
<h1>Adminzone</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="admins-tab" data-toggle="tab" href="#admins" role="tab" aria-controls="admins" aria-selected="true">Administradores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="device-reports" data-toggle="tab" href="#reports" role="tab" aria-controls="reports" aria-selected="true">Reportes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="device-models-tab" data-toggle="tab" href="#device-models" role="tab" aria-controls="device-models" aria-selected="true">Modelos de Equipo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="offices-tab" data-toggle="tab" href="#offices" role="tab" aria-controls="offices" aria-selected="false">Oficinas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="plans-tab" data-toggle="tab" href="#plans" role="tab" aria-controls="plans" aria-selected="false">Planes de celulares</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="accounts-tab" data-toggle="tab" href="#accounts" role="tab" aria-controls="accounts" aria-selected="false">Cuentas de celulares</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="telephone-switches-tab" data-toggle="tab" href="#telephone-switches" role="tab" aria-controls="accounts" aria-selected="false">Centrales</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="form-options-tab" data-toggle="tab" href="#form-options" role="tab" aria-controls="form-options" aria-selected="false">Opciones para formularios</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="admins" role="tabpanel" aria-labelledby="admins-tab">
    <%= render "admins_table" %>
  </div>

  <div class="tab-pane fade show" id="reports" role="tabpanel" aria-labelledby="reports-tab">
    <%= link_to "Nuevo Reporte", new_report_path, remote: :true, class:"btn btn-success" %>
    <%= render "reports_table" %>
    <div class="" id="new-report">
    </div>
  </div>

  <div class="tab-pane fade show" id="device-models" role="tabpanel" aria-labelledby="device-models-tab">
    <%= link_to "Nuevo modelo de equipo", new_device_model_path, remote: :true, class:"btn btn-success" %>
    <%= render "device_models_table" %>
    <div class="" id="new-device-model">
    </div>
  </div>

  <div class="tab-pane fade" id="offices" role="tabpanel" aria-labelledby="offices-tab">
    <%= link_to "Nueva Oficina", new_office_path, remote: :true, class:"btn btn-success" %>
    <%= render "offices_table" %>
    <div class="" id="form-office">
    </div>
  </div>

  <div class="tab-pane fade" id="plans" role="tabpanel" aria-labelledby="plans-tab">
    <%= link_to "Nuevo plan celular", new_plan_path, remote: :true, class:"btn btn-success" %>
    <%= render "plans_table" %>
    <div class="" id="new-plan">
    </div>
  </div>

  <div class="tab-pane fade" id="accounts" role="tabpanel" aria-labelledby="accounts-tab">
    <%= link_to "Nueva cuenta (líneas)", new_account_path, remote: :true, class:"btn btn-success" %>
    <%= render "accounts_table" %>
    <div class="" id="new-account">
    </div>

  </div>

  <div class="tab-pane fade" id="telephone-switches" role="tabpanel" aria-labelledby="telephone-switches-tab">
    <%= link_to "Nueva central (líneas)", new_telephone_switch_path, remote: :true, class:"btn btn-success" %>
    <%= render "telephone_switches_table" %>
    <div class="" id="form-telephone-switch">
    </div>

  </div>

  <div class="tab-pane fade" id="form-options" role="tabpanel" aria-labelledby="form-options-tab">
    <%= link_to "Nueva opción de formulario", new_form_option_path, remote: :true, class:"btn btn-success" %>
    <%= render "form_options_table" %>
    <div class="" id="form-form-option">

    </div>
  </div>
</div>